---
- hosts: hostgroup
  sudo: yes
  vars:
    http_port: 80
    domain: test.com

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enable mod rewrite module
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 to listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: replace default html with hello world page
      template: src=index.html dest=/var/www/html/index.html

    - name: Enable {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
